-- MySQL Script generated by MySQL Workbench
-- Fri Mar 29 16:46:39 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Manager` (
  `idManager` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `AFM` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idManager`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MovieParticipant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MovieParticipant` (
  `idMovieParticipant` INT NOT NULL,
  PRIMARY KEY (`idMovieParticipant`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Actors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Actors` (
  `idActors` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `ActingEducation` ENUM('ActingSchool', 'Acting&Working', 'SelfTaughtActor') NOT NULL,
  `BirthDate` DATE NOT NULL,
  `Sex` VARCHAR(45) NOT NULL,
  `Nationality` VARCHAR(45) NOT NULL,
  `Manager_idManager` INT NULL,
  `Actors_idActors` INT NULL,
  `MovieParticipant_idMovieParticipant` INT NOT NULL,
  PRIMARY KEY (`idActors`),
  INDEX `fk_Actors_Manager1_idx` (`Manager_idManager` ASC),
  INDEX `fk_Actors_Actors1_idx` (`Actors_idActors` ASC),
  INDEX `fk_Actors_MovieParticipant1_idx` (`MovieParticipant_idMovieParticipant` ASC),
  CONSTRAINT `fk_Actors_Manager1`
    FOREIGN KEY (`Manager_idManager`)
    REFERENCES `mydb`.`Manager` (`idManager`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actors_Actors1`
    FOREIGN KEY (`Actors_idActors`)
    REFERENCES `mydb`.`Actors` (`idActors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actors_MovieParticipant1`
    FOREIGN KEY (`MovieParticipant_idMovieParticipant`)
    REFERENCES `mydb`.`MovieParticipant` (`idMovieParticipant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MovieProductionCompany`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MovieProductionCompany` (
  `idMovieProductionCompany` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Website` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Ethnicity` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMovieProductionCompany`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contract` (
  `idContract` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Length` VARCHAR(45) NOT NULL,
  `Payment` VARCHAR(45) NOT NULL,
  `ManagerPayment` VARCHAR(45) NULL,
  `Actors_idActors` INT NOT NULL,
  `MovieProductionCompany_idMovieProductionCompany` INT NOT NULL,
  PRIMARY KEY (`idContract`, `Actors_idActors`, `MovieProductionCompany_idMovieProductionCompany`),
  INDEX `fk_Contract_Actors1_idx` (`Actors_idActors` ASC),
  INDEX `fk_Contract_MovieProductionCompany1_idx` (`MovieProductionCompany_idMovieProductionCompany` ASC),
  CONSTRAINT `fk_Contract_Actors1`
    FOREIGN KEY (`Actors_idActors`)
    REFERENCES `mydb`.`Actors` (`idActors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contract_MovieProductionCompany1`
    FOREIGN KEY (`MovieProductionCompany_idMovieProductionCompany`)
    REFERENCES `mydb`.`MovieProductionCompany` (`idMovieProductionCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Director` (
  `idDirector` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `BirthDate` DATE NOT NULL,
  `Sex` VARCHAR(45) NOT NULL,
  `Ethnicity` VARCHAR(45) NOT NULL,
  `MovieParticipant_idMovieParticipant` INT NOT NULL,
  PRIMARY KEY (`idDirector`),
  INDEX `fk_Director_MovieParticipant1_idx` (`MovieParticipant_idMovieParticipant` ASC),
  CONSTRAINT `fk_Director_MovieParticipant1`
    FOREIGN KEY (`MovieParticipant_idMovieParticipant`)
    REFERENCES `mydb`.`MovieParticipant` (`idMovieParticipant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Movie` (
  `idMovie` INT NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  `Genre` VARCHAR(45) NOT NULL,
  `ReleaseDate` DATE NOT NULL,
  `Length` VARCHAR(45) NOT NULL,
  `Colored` TINYINT(1) NOT NULL,
  `StartofProdcution` DATE NOT NULL,
  `EndofProduction` DATE NOT NULL,
  `Ethnicity` VARCHAR(45) NOT NULL,
  `Movie_idMovie` INT NULL,
  `Movie_MovieProductionCompany_idMovieProductionCompany` INT NULL,
  `Movie_Director_idDirector` INT NULL,
  `Director_idDirector` INT NOT NULL,
  `MovieProductionCompany_idMovieProductionCompany` INT NOT NULL,
  PRIMARY KEY (`idMovie`, `Director_idDirector`, `MovieProductionCompany_idMovieProductionCompany`),
  INDEX `fk_Movie_Director1_idx` (`Director_idDirector` ASC),
  INDEX `fk_Movie_MovieProductionCompany1_idx` (`MovieProductionCompany_idMovieProductionCompany` ASC),
  INDEX `fk_Movie_Movie1_idx` (`Movie_idMovie` ASC, `Movie_Director_idDirector` ASC, `Movie_MovieProductionCompany_idMovieProductionCompany` ASC),
  CONSTRAINT `fk_Movie_Director1`
    FOREIGN KEY (`Director_idDirector`)
    REFERENCES `mydb`.`Director` (`idDirector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_MovieProductionCompany1`
    FOREIGN KEY (`MovieProductionCompany_idMovieProductionCompany`)
    REFERENCES `mydb`.`MovieProductionCompany` (`idMovieProductionCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_Movie1`
    FOREIGN KEY (`Movie_idMovie` , `Movie_Director_idDirector` , `Movie_MovieProductionCompany_idMovieProductionCompany`)
    REFERENCES `mydb`.`Movie` (`idMovie` , `Director_idDirector` , `MovieProductionCompany_idMovieProductionCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Movie_has_Actors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Movie_has_Actors` (
  `Movie_idMovie` INT NOT NULL,
  `Actors_idActors` INT NOT NULL,
  PRIMARY KEY (`Movie_idMovie`, `Actors_idActors`),
  INDEX `fk_Movie_has_Actors_Actors1_idx` (`Actors_idActors` ASC),
  INDEX `fk_Movie_has_Actors_Movie1_idx` (`Movie_idMovie` ASC),
  CONSTRAINT `fk_Movie_has_Actors_Movie1`
    FOREIGN KEY (`Movie_idMovie`)
    REFERENCES `mydb`.`Movie` (`idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_has_Actors_Actors1`
    FOREIGN KEY (`Actors_idActors`)
    REFERENCES `mydb`.`Actors` (`idActors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Role` (
  `idRole` INT NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Description` MEDIUMTEXT NOT NULL,
  `Actors_idActors` INT NOT NULL,
  `Movie_idMovie` INT NOT NULL,
  PRIMARY KEY (`idRole`, `Movie_idMovie`),
  INDEX `fk_Role_Actors1_idx` (`Actors_idActors` ASC),
  INDEX `fk_Role_Movie1_idx` (`Movie_idMovie` ASC),
  CONSTRAINT `fk_Role_Actors1`
    FOREIGN KEY (`Actors_idActors`)
    REFERENCES `mydb`.`Actors` (`idActors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Role_Movie1`
    FOREIGN KEY (`Movie_idMovie`)
    REFERENCES `mydb`.`Movie` (`idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ScriptWriter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ScriptWriter` (
  `idScriptWriter` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `BirthDate` DATE NOT NULL,
  `Sex` VARCHAR(45) NOT NULL,
  `Ethnicity` VARCHAR(45) NOT NULL,
  `MovieParticipant_idMovieParticipant` INT NOT NULL,
  PRIMARY KEY (`idScriptWriter`),
  INDEX `fk_ScriptWriter_MovieParticipant1_idx` (`MovieParticipant_idMovieParticipant` ASC),
  CONSTRAINT `fk_ScriptWriter_MovieParticipant1`
    FOREIGN KEY (`MovieParticipant_idMovieParticipant`)
    REFERENCES `mydb`.`MovieParticipant` (`idMovieParticipant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Studio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Studio` (
  `idStudio` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Location` VARCHAR(45) NOT NULL,
  `Size` VARCHAR(45) NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStudio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Movie_Social_Network_Site`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Movie_Social_Network_Site` (
  `idMovie_Social_Network_Site` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Movie_idMovie` INT NOT NULL,
  PRIMARY KEY (`idMovie_Social_Network_Site`, `Movie_idMovie`),
  INDEX `fk_Movie_Social_Network_Site_Movie1_idx` (`Movie_idMovie` ASC),
  CONSTRAINT `fk_Movie_Social_Network_Site_Movie1`
    FOREIGN KEY (`Movie_idMovie`)
    REFERENCES `mydb`.`Movie` (`idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Photo` (
  `idPhoto` INT NOT NULL,
  `Description` MEDIUMTEXT NOT NULL,
  `Movie_Social_Network_Site_idMovie_Social_Network_Site` INT NOT NULL,
  `Movie_Social_Network_Site_Movie_idMovie` INT NOT NULL,
  PRIMARY KEY (`idPhoto`, `Movie_Social_Network_Site_idMovie_Social_Network_Site`, `Movie_Social_Network_Site_Movie_idMovie`),
  INDEX `fk_Photo_Movie_Social_Network_Site1_idx` (`Movie_Social_Network_Site_idMovie_Social_Network_Site` ASC, `Movie_Social_Network_Site_Movie_idMovie` ASC),
  CONSTRAINT `fk_Photo_Movie_Social_Network_Site1`
    FOREIGN KEY (`Movie_Social_Network_Site_idMovie_Social_Network_Site` , `Movie_Social_Network_Site_Movie_idMovie`)
    REFERENCES `mydb`.`Movie_Social_Network_Site` (`idMovie_Social_Network_Site` , `Movie_idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Technician`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Technician` (
  `idTechnician` INT NOT NULL,
  `Specialization` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Age` VARCHAR(45) NOT NULL,
  `Ethnicity` VARCHAR(45) NOT NULL,
  `MovieParticipant_idMovieParticipant` INT NOT NULL,
  PRIMARY KEY (`idTechnician`),
  INDEX `fk_Technician_MovieParticipant1_idx` (`MovieParticipant_idMovieParticipant` ASC),
  CONSTRAINT `fk_Technician_MovieParticipant1`
    FOREIGN KEY (`MovieParticipant_idMovieParticipant`)
    REFERENCES `mydb`.`MovieParticipant` (`idMovieParticipant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Movie_has_Technician`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Movie_has_Technician` (
  `Movie_idMovie` INT NOT NULL,
  `Movie_MovieProductionCompany_idMovieProductionCompany` INT NOT NULL,
  `Technician_idTechnician` INT NOT NULL,
  PRIMARY KEY (`Movie_idMovie`, `Movie_MovieProductionCompany_idMovieProductionCompany`, `Technician_idTechnician`),
  INDEX `fk_Movie_has_Technician_Technician1_idx` (`Technician_idTechnician` ASC),
  INDEX `fk_Movie_has_Technician_Movie1_idx` (`Movie_idMovie` ASC, `Movie_MovieProductionCompany_idMovieProductionCompany` ASC),
  CONSTRAINT `fk_Movie_has_Technician_Movie1`
    FOREIGN KEY (`Movie_idMovie` , `Movie_MovieProductionCompany_idMovieProductionCompany`)
    REFERENCES `mydb`.`Movie` (`idMovie` , `MovieProductionCompany_idMovieProductionCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_has_Technician_Technician1`
    FOREIGN KEY (`Technician_idTechnician`)
    REFERENCES `mydb`.`Technician` (`idTechnician`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Movie_has_ScriptWriter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Movie_has_ScriptWriter` (
  `Movie_idMovie` INT NOT NULL,
  `Movie_Director_idDirector` INT NOT NULL,
  `ScriptWriter_idScriptWriter` INT NOT NULL,
  PRIMARY KEY (`Movie_idMovie`, `Movie_Director_idDirector`, `ScriptWriter_idScriptWriter`),
  INDEX `fk_Movie_has_ScriptWriter1_ScriptWriter1_idx` (`ScriptWriter_idScriptWriter` ASC),
  INDEX `fk_Movie_has_ScriptWriter1_Movie1_idx` (`Movie_idMovie` ASC, `Movie_Director_idDirector` ASC),
  CONSTRAINT `fk_Movie_has_ScriptWriter1_Movie1`
    FOREIGN KEY (`Movie_idMovie` , `Movie_Director_idDirector`)
    REFERENCES `mydb`.`Movie` (`idMovie` , `Director_idDirector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_has_ScriptWriter1_ScriptWriter1`
    FOREIGN KEY (`ScriptWriter_idScriptWriter`)
    REFERENCES `mydb`.`ScriptWriter` (`idScriptWriter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Movie_has_Studio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Movie_has_Studio` (
  `Movie_idMovie` INT NOT NULL,
  `Movie_MovieProductionCompany_idMovieProductionCompany` INT NOT NULL,
  `Studio_idStudio` INT NOT NULL,
  PRIMARY KEY (`Movie_idMovie`, `Movie_MovieProductionCompany_idMovieProductionCompany`, `Studio_idStudio`),
  INDEX `fk_Movie_has_Studio_Studio1_idx` (`Studio_idStudio` ASC),
  INDEX `fk_Movie_has_Studio_Movie1_idx` (`Movie_idMovie` ASC, `Movie_MovieProductionCompany_idMovieProductionCompany` ASC),
  CONSTRAINT `fk_Movie_has_Studio_Movie1`
    FOREIGN KEY (`Movie_idMovie` , `Movie_MovieProductionCompany_idMovieProductionCompany`)
    REFERENCES `mydb`.`Movie` (`idMovie` , `MovieProductionCompany_idMovieProductionCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_has_Studio_Studio1`
    FOREIGN KEY (`Studio_idStudio`)
    REFERENCES `mydb`.`Studio` (`idStudio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Friends` (
  `MovieParticipant_idMovieParticipant1` INT NOT NULL,
  `MovieParticipant_idMovieParticipant` INT NOT NULL,
  PRIMARY KEY (`MovieParticipant_idMovieParticipant1`, `MovieParticipant_idMovieParticipant`),
  INDEX `fk_MovieParticipant_has_MovieParticipant_MovieParticipant2_idx` (`MovieParticipant_idMovieParticipant1` ASC),
  INDEX `fk_MovieParticipant_has_MovieParticipant_MovieParticipant1_idx` (`MovieParticipant_idMovieParticipant` ASC),
  CONSTRAINT `fk_MovieParticipant_has_MovieParticipant_MovieParticipant1`
    FOREIGN KEY (`MovieParticipant_idMovieParticipant`)
    REFERENCES `mydb`.`MovieParticipant` (`idMovieParticipant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MovieParticipant_has_MovieParticipant_MovieParticipant2`
    FOREIGN KEY (`MovieParticipant_idMovieParticipant1`)
    REFERENCES `mydb`.`MovieParticipant` (`idMovieParticipant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Movie_Social_Network_Site_has_MovieParticipant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Movie_Social_Network_Site_has_MovieParticipant` (
  `Movie_Social_Network_Site_idMovie_Social_Network_Site` INT NOT NULL,
  `Movie_Social_Network_Site_Movie_idMovie` INT NOT NULL,
  `MovieParticipant_idMovieParticipant` INT NOT NULL,
  PRIMARY KEY (`Movie_Social_Network_Site_idMovie_Social_Network_Site`, `Movie_Social_Network_Site_Movie_idMovie`, `MovieParticipant_idMovieParticipant`),
  INDEX `fk_Movie_Social_Network_Site_has_MovieParticipant_MoviePart_idx` (`MovieParticipant_idMovieParticipant` ASC),
  INDEX `fk_Movie_Social_Network_Site_has_MovieParticipant_Movie_Soc_idx` (`Movie_Social_Network_Site_idMovie_Social_Network_Site` ASC, `Movie_Social_Network_Site_Movie_idMovie` ASC),
  CONSTRAINT `fk_Movie_Social_Network_Site_has_MovieParticipant_Movie_Socia1`
    FOREIGN KEY (`Movie_Social_Network_Site_idMovie_Social_Network_Site` , `Movie_Social_Network_Site_Movie_idMovie`)
    REFERENCES `mydb`.`Movie_Social_Network_Site` (`idMovie_Social_Network_Site` , `Movie_idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_Social_Network_Site_has_MovieParticipant_MoviePartic1`
    FOREIGN KEY (`MovieParticipant_idMovieParticipant`)
    REFERENCES `mydb`.`MovieParticipant` (`idMovieParticipant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Photo_has_MovieParticipant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Photo_has_MovieParticipant` (
  `Photo_idPhoto` INT NOT NULL,
  `Photo_Movie_Social_Network_Site_idMovie_Social_Network_Site` INT NOT NULL,
  `Photo_Movie_Social_Network_Site_Movie_idMovie` INT NOT NULL,
  `MovieParticipant_idMovieParticipant` INT NOT NULL,
  PRIMARY KEY (`Photo_idPhoto`, `Photo_Movie_Social_Network_Site_idMovie_Social_Network_Site`, `Photo_Movie_Social_Network_Site_Movie_idMovie`, `MovieParticipant_idMovieParticipant`),
  INDEX `fk_Photo_has_MovieParticipant_MovieParticipant1_idx` (`MovieParticipant_idMovieParticipant` ASC),
  INDEX `fk_Photo_has_MovieParticipant_Photo1_idx` (`Photo_idPhoto` ASC, `Photo_Movie_Social_Network_Site_idMovie_Social_Network_Site` ASC, `Photo_Movie_Social_Network_Site_Movie_idMovie` ASC),
  CONSTRAINT `fk_Photo_has_MovieParticipant_Photo1`
    FOREIGN KEY (`Photo_idPhoto` , `Photo_Movie_Social_Network_Site_idMovie_Social_Network_Site` , `Photo_Movie_Social_Network_Site_Movie_idMovie`)
    REFERENCES `mydb`.`Photo` (`idPhoto` , `Movie_Social_Network_Site_idMovie_Social_Network_Site` , `Movie_Social_Network_Site_Movie_idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Photo_has_MovieParticipant_MovieParticipant1`
    FOREIGN KEY (`MovieParticipant_idMovieParticipant`)
    REFERENCES `mydb`.`MovieParticipant` (`idMovieParticipant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Academy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Academy` (
  `idAcademy` INT NOT NULL,
  PRIMARY KEY (`idAcademy`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Branch` (
  `idBranch` INT NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Academy_idAcademy` INT NOT NULL,
  PRIMARY KEY (`idBranch`, `Academy_idAcademy`),
  INDEX `fk_Branch_Academy1_idx` (`Academy_idAcademy` ASC),
  CONSTRAINT `fk_Branch_Academy1`
    FOREIGN KEY (`Academy_idAcademy`)
    REFERENCES `mydb`.`Academy` (`idAcademy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MemberofBranch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MemberofBranch` (
  `idMemberofBranch` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `YearsofMembership` INT NOT NULL,
  `Branch_idBranch` INT NOT NULL,
  `Branch_Academy_idAcademy` INT NOT NULL,
  PRIMARY KEY (`idMemberofBranch`, `Branch_idBranch`, `Branch_Academy_idAcademy`),
  INDEX `fk_MemberofAcademy_Branch1_idx` (`Branch_idBranch` ASC, `Branch_Academy_idAcademy` ASC),
  CONSTRAINT `fk_MemberofAcademy_Branch1`
    FOREIGN KEY (`Branch_idBranch` , `Branch_Academy_idAcademy`)
    REFERENCES `mydb`.`Branch` (`idBranch` , `Academy_idAcademy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BoardOfDirectors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BoardOfDirectors` (
  `idBoardOfDirectors` INT NOT NULL,
  PRIMARY KEY (`idBoardOfDirectors`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AcademyChairman`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AcademyChairman` (
  `idAcademyChairman` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `ServiceYear` DATE NOT NULL,
  `Academy_idAcademy` INT NOT NULL,
  `BoardOfDirectors_idBoardOfDirectors` INT NOT NULL,
  PRIMARY KEY (`idAcademyChairman`, `Academy_idAcademy`),
  INDEX `fk_AcademyChairman_Academy1_idx` (`Academy_idAcademy` ASC),
  INDEX `fk_AcademyChairman_BoardOfDirectors1_idx` (`BoardOfDirectors_idBoardOfDirectors` ASC),
  CONSTRAINT `fk_AcademyChairman_Academy1`
    FOREIGN KEY (`Academy_idAcademy`)
    REFERENCES `mydb`.`Academy` (`idAcademy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AcademyChairman_BoardOfDirectors1`
    FOREIGN KEY (`BoardOfDirectors_idBoardOfDirectors`)
    REFERENCES `mydb`.`BoardOfDirectors` (`idBoardOfDirectors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BranchChairman`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BranchChairman` (
  `idBranchChairman` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `ServiceYear` VARCHAR(45) NOT NULL,
  `BoardOfDirectors_idBoardOfDirectors` INT NOT NULL,
  `Branch_idBranch` INT NOT NULL,
  `Branch_Academy_idAcademy` INT NOT NULL,
  PRIMARY KEY (`idBranchChairman`, `Branch_idBranch`, `Branch_Academy_idAcademy`),
  INDEX `fk_BranchChairman_BoardOfDirectors1_idx` (`BoardOfDirectors_idBoardOfDirectors` ASC),
  INDEX `fk_BranchChairman_Branch1_idx` (`Branch_idBranch` ASC, `Branch_Academy_idAcademy` ASC),
  CONSTRAINT `fk_BranchChairman_BoardOfDirectors1`
    FOREIGN KEY (`BoardOfDirectors_idBoardOfDirectors`)
    REFERENCES `mydb`.`BoardOfDirectors` (`idBoardOfDirectors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BranchChairman_Branch1`
    FOREIGN KEY (`Branch_idBranch` , `Branch_Academy_idAcademy`)
    REFERENCES `mydb`.`Branch` (`idBranch` , `Academy_idAcademy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AcademyCandidates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AcademyCandidates` (
  `idAcademyCandidates` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Specialization` VARCHAR(45) NOT NULL,
  `Suggested` TINYINT(1) NOT NULL,
  `ExNominee` TINYINT(1) NOT NULL,
  `Branch_idBranch` INT NOT NULL,
  `Branch_Academy_idAcademy` INT NOT NULL,
  `MovieParticipant_idMovieParticipant` INT NOT NULL,
  PRIMARY KEY (`idAcademyCandidates`),
  INDEX `fk_AcademyCandidates_Branch1_idx` (`Branch_idBranch` ASC, `Branch_Academy_idAcademy` ASC),
  INDEX `fk_AcademyCandidates_MovieParticipant1_idx` (`MovieParticipant_idMovieParticipant` ASC),
  CONSTRAINT `fk_AcademyCandidates_Branch1`
    FOREIGN KEY (`Branch_idBranch` , `Branch_Academy_idAcademy`)
    REFERENCES `mydb`.`Branch` (`idBranch` , `Academy_idAcademy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AcademyCandidates_MovieParticipant1`
    FOREIGN KEY (`MovieParticipant_idMovieParticipant`)
    REFERENCES `mydb`.`MovieParticipant` (`idMovieParticipant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nominee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nominee` (
  `idNominee` INT NOT NULL,
  `MovieParticipant_idMovieParticipant` INT NOT NULL,
  PRIMARY KEY (`idNominee`),
  INDEX `fk_Nominee_MovieParticipant1_idx` (`MovieParticipant_idMovieParticipant` ASC),
  CONSTRAINT `fk_Nominee_MovieParticipant1`
    FOREIGN KEY (`MovieParticipant_idMovieParticipant`)
    REFERENCES `mydb`.`MovieParticipant` (`idMovieParticipant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`IndividualOscar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`IndividualOscar` (
  `idIndividualOscar` INT NOT NULL,
  `Catergory` ENUM('2', '3', '4', '5', '6', '7', '8', '10', '11', '12', '15', '16', '17', '18') NOT NULL,
  `Year` YEAR NOT NULL,
  `Nominee_idNominee` INT NOT NULL,
  INDEX `fk_Oscar_Nominee1_idx` (`Nominee_idNominee` ASC),
  PRIMARY KEY (`idIndividualOscar`),
  CONSTRAINT `fk_Oscar_Nominee1`
    FOREIGN KEY (`Nominee_idNominee`)
    REFERENCES `mydb`.`Nominee` (`idNominee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MovieNominee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MovieNominee` (
  `idMovieNominee` INT NOT NULL,
  `Movie_idMovie` INT NOT NULL,
  `Movie_Director_idDirector` INT NOT NULL,
  `Movie_MovieProductionCompany_idMovieProductionCompany` INT NOT NULL,
  PRIMARY KEY (`idMovieNominee`),
  INDEX `fk_MovieNominee_Movie1_idx` (`Movie_idMovie` ASC, `Movie_Director_idDirector` ASC, `Movie_MovieProductionCompany_idMovieProductionCompany` ASC),
  CONSTRAINT `fk_MovieNominee_Movie1`
    FOREIGN KEY (`Movie_idMovie` , `Movie_Director_idDirector` , `Movie_MovieProductionCompany_idMovieProductionCompany`)
    REFERENCES `mydb`.`Movie` (`idMovie` , `Director_idDirector` , `MovieProductionCompany_idMovieProductionCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MovieOscar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MovieOscar` (
  `idMovieOscar` INT NOT NULL,
  `Category` ENUM('1', '9', '13', '14', '19', '20', '21') NOT NULL,
  `Year` YEAR NOT NULL,
  `MovieNominee_idMovieNominee` INT NOT NULL,
  PRIMARY KEY (`idMovieOscar`),
  INDEX `fk_MovieOscar_MovieNominee1_idx` (`MovieNominee_idMovieNominee` ASC),
  CONSTRAINT `fk_MovieOscar_MovieNominee1`
    FOREIGN KEY (`MovieNominee_idMovieNominee`)
    REFERENCES `mydb`.`MovieNominee` (`idMovieNominee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MovieGenre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MovieGenre` (
  `idMovieGenre` INT NOT NULL,
  `Name` ENUM('COMEDY', 'DRAMA', 'ADVENTURE', 'ACTION', 'SCIFI', 'ROMANCE', 'MUSICAL', 'HORROR', 'MYSTERY', 'ANIMATION', 'DOCUMENTARY') NOT NULL,
  PRIMARY KEY (`idMovieGenre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Movie_has_MovieGenre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Movie_has_MovieGenre` (
  `Movie_idMovie` INT NOT NULL,
  `Movie_Director_idDirector` INT NOT NULL,
  `Movie_MovieProductionCompany_idMovieProductionCompany` INT NOT NULL,
  `MovieGenre_idMovieGenre` INT NOT NULL,
  PRIMARY KEY (`Movie_idMovie`, `Movie_Director_idDirector`, `Movie_MovieProductionCompany_idMovieProductionCompany`, `MovieGenre_idMovieGenre`),
  INDEX `fk_Movie_has_MovieGenre_MovieGenre1_idx` (`MovieGenre_idMovieGenre` ASC),
  INDEX `fk_Movie_has_MovieGenre_Movie1_idx` (`Movie_idMovie` ASC, `Movie_Director_idDirector` ASC, `Movie_MovieProductionCompany_idMovieProductionCompany` ASC),
  CONSTRAINT `fk_Movie_has_MovieGenre_Movie1`
    FOREIGN KEY (`Movie_idMovie` , `Movie_Director_idDirector` , `Movie_MovieProductionCompany_idMovieProductionCompany`)
    REFERENCES `mydb`.`Movie` (`idMovie` , `Director_idDirector` , `MovieProductionCompany_idMovieProductionCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_has_MovieGenre_MovieGenre1`
    FOREIGN KEY (`MovieGenre_idMovieGenre`)
    REFERENCES `mydb`.`MovieGenre` (`idMovieGenre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
